server:
  port: 8888
  nettyPort: 1234
  nettySoBackLog: 1024

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/connectComputer?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    password: 123456

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  application:
    name: ConnectComputer_server

language: zh_cn.json
defaultAvatar: avatar/default_avatar.jpg
avatarFileMaxSizeInKb: 5120
avatarFilePath: avatar
tokenExpiredTime: 2592000000
nettyTokenExpiredTime: 86400000