// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Action/Computer/Security/security.proto

package cn.gdrfgdrf.Protobuf.Action.Computer.Security;

public final class ComputerSecurityProto {
  private ComputerSecurityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExchangeRsaPublicKeyPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.ExchangeRsaPublicKeyPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string public_key = 1;</code>
     * @return The publicKey.
     */
    java.lang.String getPublicKey();
    /**
     * <code>string public_key = 1;</code>
     * @return The bytes for publicKey.
     */
    com.google.protobuf.ByteString
        getPublicKeyBytes();
  }
  /**
   * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.ExchangeRsaPublicKeyPacket}
   */
  public static final class ExchangeRsaPublicKeyPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.ExchangeRsaPublicKeyPacket)
      ExchangeRsaPublicKeyPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExchangeRsaPublicKeyPacket.newBuilder() to construct.
    private ExchangeRsaPublicKeyPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExchangeRsaPublicKeyPacket() {
      publicKey_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExchangeRsaPublicKeyPacket();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_ExchangeRsaPublicKeyPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_ExchangeRsaPublicKeyPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket.class, cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket.Builder.class);
    }

    public static final int PUBLIC_KEY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object publicKey_ = "";
    /**
     * <code>string public_key = 1;</code>
     * @return The publicKey.
     */
    @java.lang.Override
    public java.lang.String getPublicKey() {
      java.lang.Object ref = publicKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        publicKey_ = s;
        return s;
      }
    }
    /**
     * <code>string public_key = 1;</code>
     * @return The bytes for publicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPublicKeyBytes() {
      java.lang.Object ref = publicKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publicKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(publicKey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, publicKey_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(publicKey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, publicKey_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket)) {
        return super.equals(obj);
      }
      cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket other = (cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket) obj;

      if (!getPublicKey()
          .equals(other.getPublicKey())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PUBLIC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKey().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.ExchangeRsaPublicKeyPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.ExchangeRsaPublicKeyPacket)
        cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_ExchangeRsaPublicKeyPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_ExchangeRsaPublicKeyPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket.class, cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket.Builder.class);
      }

      // Construct using cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        publicKey_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_ExchangeRsaPublicKeyPacket_descriptor;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket getDefaultInstanceForType() {
        return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket.getDefaultInstance();
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket build() {
        cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket buildPartial() {
        cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket result = new cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.publicKey_ = publicKey_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket) {
          return mergeFrom((cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket other) {
        if (other == cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket.getDefaultInstance()) return this;
        if (!other.getPublicKey().isEmpty()) {
          publicKey_ = other.publicKey_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                publicKey_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object publicKey_ = "";
      /**
       * <code>string public_key = 1;</code>
       * @return The publicKey.
       */
      public java.lang.String getPublicKey() {
        java.lang.Object ref = publicKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          publicKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string public_key = 1;</code>
       * @return The bytes for publicKey.
       */
      public com.google.protobuf.ByteString
          getPublicKeyBytes() {
        java.lang.Object ref = publicKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          publicKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string public_key = 1;</code>
       * @param value The publicKey to set.
       * @return This builder for chaining.
       */
      public Builder setPublicKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        publicKey_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string public_key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublicKey() {
        publicKey_ = getDefaultInstance().getPublicKey();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string public_key = 1;</code>
       * @param value The bytes for publicKey to set.
       * @return This builder for chaining.
       */
      public Builder setPublicKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        publicKey_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.ExchangeRsaPublicKeyPacket)
    }

    // @@protoc_insertion_point(class_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.ExchangeRsaPublicKeyPacket)
    private static final cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket();
    }

    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExchangeRsaPublicKeyPacket>
        PARSER = new com.google.protobuf.AbstractParser<ExchangeRsaPublicKeyPacket>() {
      @java.lang.Override
      public ExchangeRsaPublicKeyPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ExchangeRsaPublicKeyPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExchangeRsaPublicKeyPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.ExchangeRsaPublicKeyPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AesKeyReceivedPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.AesKeyReceivedPacket)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.AesKeyReceivedPacket}
   */
  public static final class AesKeyReceivedPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.AesKeyReceivedPacket)
      AesKeyReceivedPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AesKeyReceivedPacket.newBuilder() to construct.
    private AesKeyReceivedPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AesKeyReceivedPacket() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AesKeyReceivedPacket();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_AesKeyReceivedPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_AesKeyReceivedPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket.class, cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket)) {
        return super.equals(obj);
      }
      cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket other = (cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.AesKeyReceivedPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.AesKeyReceivedPacket)
        cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_AesKeyReceivedPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_AesKeyReceivedPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket.class, cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket.Builder.class);
      }

      // Construct using cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_AesKeyReceivedPacket_descriptor;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket getDefaultInstanceForType() {
        return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket.getDefaultInstance();
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket build() {
        cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket buildPartial() {
        cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket result = new cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket) {
          return mergeFrom((cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket other) {
        if (other == cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.AesKeyReceivedPacket)
    }

    // @@protoc_insertion_point(class_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.AesKeyReceivedPacket)
    private static final cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket();
    }

    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AesKeyReceivedPacket>
        PARSER = new com.google.protobuf.AbstractParser<AesKeyReceivedPacket>() {
      @java.lang.Override
      public AesKeyReceivedPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AesKeyReceivedPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AesKeyReceivedPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.AesKeyReceivedPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EncryptBlockPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.EncryptBlockPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Security.EncryptAlgorithmEnum encrypt_algorithm = 1;</code>
     * @return The enum numeric value on the wire for encryptAlgorithm.
     */
    int getEncryptAlgorithmValue();
    /**
     * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Security.EncryptAlgorithmEnum encrypt_algorithm = 1;</code>
     * @return The encryptAlgorithm.
     */
    cn.gdrfgdrf.Protobuf.Security.SecurityEnumProto.EncryptAlgorithmEnum getEncryptAlgorithm();

    /**
     * <code>bytes encrypted = 2;</code>
     * @return The encrypted.
     */
    com.google.protobuf.ByteString getEncrypted();
  }
  /**
   * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.EncryptBlockPacket}
   */
  public static final class EncryptBlockPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.EncryptBlockPacket)
      EncryptBlockPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EncryptBlockPacket.newBuilder() to construct.
    private EncryptBlockPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EncryptBlockPacket() {
      encryptAlgorithm_ = 0;
      encrypted_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EncryptBlockPacket();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_EncryptBlockPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_EncryptBlockPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket.class, cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket.Builder.class);
    }

    public static final int ENCRYPT_ALGORITHM_FIELD_NUMBER = 1;
    private int encryptAlgorithm_ = 0;
    /**
     * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Security.EncryptAlgorithmEnum encrypt_algorithm = 1;</code>
     * @return The enum numeric value on the wire for encryptAlgorithm.
     */
    @java.lang.Override public int getEncryptAlgorithmValue() {
      return encryptAlgorithm_;
    }
    /**
     * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Security.EncryptAlgorithmEnum encrypt_algorithm = 1;</code>
     * @return The encryptAlgorithm.
     */
    @java.lang.Override public cn.gdrfgdrf.Protobuf.Security.SecurityEnumProto.EncryptAlgorithmEnum getEncryptAlgorithm() {
      cn.gdrfgdrf.Protobuf.Security.SecurityEnumProto.EncryptAlgorithmEnum result = cn.gdrfgdrf.Protobuf.Security.SecurityEnumProto.EncryptAlgorithmEnum.forNumber(encryptAlgorithm_);
      return result == null ? cn.gdrfgdrf.Protobuf.Security.SecurityEnumProto.EncryptAlgorithmEnum.UNRECOGNIZED : result;
    }

    public static final int ENCRYPTED_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString encrypted_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes encrypted = 2;</code>
     * @return The encrypted.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncrypted() {
      return encrypted_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (encryptAlgorithm_ != cn.gdrfgdrf.Protobuf.Security.SecurityEnumProto.EncryptAlgorithmEnum.RSA.getNumber()) {
        output.writeEnum(1, encryptAlgorithm_);
      }
      if (!encrypted_.isEmpty()) {
        output.writeBytes(2, encrypted_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (encryptAlgorithm_ != cn.gdrfgdrf.Protobuf.Security.SecurityEnumProto.EncryptAlgorithmEnum.RSA.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, encryptAlgorithm_);
      }
      if (!encrypted_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, encrypted_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket)) {
        return super.equals(obj);
      }
      cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket other = (cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket) obj;

      if (encryptAlgorithm_ != other.encryptAlgorithm_) return false;
      if (!getEncrypted()
          .equals(other.getEncrypted())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENCRYPT_ALGORITHM_FIELD_NUMBER;
      hash = (53 * hash) + encryptAlgorithm_;
      hash = (37 * hash) + ENCRYPTED_FIELD_NUMBER;
      hash = (53 * hash) + getEncrypted().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.EncryptBlockPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.EncryptBlockPacket)
        cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_EncryptBlockPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_EncryptBlockPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket.class, cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket.Builder.class);
      }

      // Construct using cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        encryptAlgorithm_ = 0;
        encrypted_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_EncryptBlockPacket_descriptor;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket getDefaultInstanceForType() {
        return cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket.getDefaultInstance();
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket build() {
        cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket buildPartial() {
        cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket result = new cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.encryptAlgorithm_ = encryptAlgorithm_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.encrypted_ = encrypted_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket) {
          return mergeFrom((cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket other) {
        if (other == cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket.getDefaultInstance()) return this;
        if (other.encryptAlgorithm_ != 0) {
          setEncryptAlgorithmValue(other.getEncryptAlgorithmValue());
        }
        if (other.getEncrypted() != com.google.protobuf.ByteString.EMPTY) {
          setEncrypted(other.getEncrypted());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                encryptAlgorithm_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                encrypted_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int encryptAlgorithm_ = 0;
      /**
       * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Security.EncryptAlgorithmEnum encrypt_algorithm = 1;</code>
       * @return The enum numeric value on the wire for encryptAlgorithm.
       */
      @java.lang.Override public int getEncryptAlgorithmValue() {
        return encryptAlgorithm_;
      }
      /**
       * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Security.EncryptAlgorithmEnum encrypt_algorithm = 1;</code>
       * @param value The enum numeric value on the wire for encryptAlgorithm to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptAlgorithmValue(int value) {
        encryptAlgorithm_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Security.EncryptAlgorithmEnum encrypt_algorithm = 1;</code>
       * @return The encryptAlgorithm.
       */
      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Security.SecurityEnumProto.EncryptAlgorithmEnum getEncryptAlgorithm() {
        cn.gdrfgdrf.Protobuf.Security.SecurityEnumProto.EncryptAlgorithmEnum result = cn.gdrfgdrf.Protobuf.Security.SecurityEnumProto.EncryptAlgorithmEnum.forNumber(encryptAlgorithm_);
        return result == null ? cn.gdrfgdrf.Protobuf.Security.SecurityEnumProto.EncryptAlgorithmEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Security.EncryptAlgorithmEnum encrypt_algorithm = 1;</code>
       * @param value The encryptAlgorithm to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptAlgorithm(cn.gdrfgdrf.Protobuf.Security.SecurityEnumProto.EncryptAlgorithmEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        encryptAlgorithm_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Security.EncryptAlgorithmEnum encrypt_algorithm = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncryptAlgorithm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        encryptAlgorithm_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString encrypted_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes encrypted = 2;</code>
       * @return The encrypted.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getEncrypted() {
        return encrypted_;
      }
      /**
       * <code>bytes encrypted = 2;</code>
       * @param value The encrypted to set.
       * @return This builder for chaining.
       */
      public Builder setEncrypted(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        encrypted_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes encrypted = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncrypted() {
        bitField0_ = (bitField0_ & ~0x00000002);
        encrypted_ = getDefaultInstance().getEncrypted();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.EncryptBlockPacket)
    }

    // @@protoc_insertion_point(class_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Computer.Security.EncryptBlockPacket)
    private static final cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket();
    }

    public static cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EncryptBlockPacket>
        PARSER = new com.google.protobuf.AbstractParser<EncryptBlockPacket>() {
      @java.lang.Override
      public EncryptBlockPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EncryptBlockPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EncryptBlockPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.gdrfgdrf.Protobuf.Action.Computer.Security.ComputerSecurityProto.EncryptBlockPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_ExchangeRsaPublicKeyPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_ExchangeRsaPublicKeyPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_AesKeyReceivedPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_AesKeyReceivedPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_EncryptBlockPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_EncryptBlockPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'Action/Computer/Security/security.prot" +
      "o\022=cn.gdrfgdrf.connectComputer.Protobuf." +
      "Action.Computer.Security\032!Security/Enum/" +
      "security_enum.proto\"0\n\032ExchangeRsaPublic" +
      "KeyPacket\022\022\n\npublic_key\030\001 \001(\t\"\026\n\024AesKeyR" +
      "eceivedPacket\"\207\001\n\022EncryptBlockPacket\022^\n\021" +
      "encrypt_algorithm\030\001 \001(\0162C.cn.gdrfgdrf.co" +
      "nnectComputer.Protobuf.Security.EncryptA" +
      "lgorithmEnum\022\021\n\tencrypted\030\002 \001(\014BF\n-cn.gd" +
      "rfgdrf.Protobuf.Action.Computer.Security" +
      "B\025ComputerSecurityProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.gdrfgdrf.Protobuf.Security.SecurityEnumProto.getDescriptor(),
        });
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_ExchangeRsaPublicKeyPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_ExchangeRsaPublicKeyPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_ExchangeRsaPublicKeyPacket_descriptor,
        new java.lang.String[] { "PublicKey", });
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_AesKeyReceivedPacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_AesKeyReceivedPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_AesKeyReceivedPacket_descriptor,
        new java.lang.String[] { });
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_EncryptBlockPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_EncryptBlockPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Computer_Security_EncryptBlockPacket_descriptor,
        new java.lang.String[] { "EncryptAlgorithm", "Encrypted", });
    cn.gdrfgdrf.Protobuf.Security.SecurityEnumProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
