// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Action/Controller/controller.proto

package cn.gdrfgdrf.Protobuf.Action.Controller;

public final class ControllerProto {
  private ControllerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConnectComputerPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.ConnectComputerPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();
  }
  /**
   * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.ConnectComputerPacket}
   */
  public static final class ConnectComputerPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.ConnectComputerPacket)
      ConnectComputerPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConnectComputerPacket.newBuilder() to construct.
    private ConnectComputerPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConnectComputerPacket() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConnectComputerPacket();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ConnectComputerPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ConnectComputerPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket.class, cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket)) {
        return super.equals(obj);
      }
      cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket other = (cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket) obj;

      if (getId()
          != other.getId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.ConnectComputerPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.ConnectComputerPacket)
        cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ConnectComputerPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ConnectComputerPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket.class, cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket.Builder.class);
      }

      // Construct using cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ConnectComputerPacket_descriptor;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket getDefaultInstanceForType() {
        return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket.getDefaultInstance();
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket build() {
        cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket buildPartial() {
        cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket result = new cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket) {
          return mergeFrom((cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket other) {
        if (other == cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.ConnectComputerPacket)
    }

    // @@protoc_insertion_point(class_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.ConnectComputerPacket)
    private static final cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket();
    }

    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConnectComputerPacket>
        PARSER = new com.google.protobuf.AbstractParser<ConnectComputerPacket>() {
      @java.lang.Override
      public ConnectComputerPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ConnectComputerPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConnectComputerPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ConnectComputerPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ControllerDisconnectedPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.ControllerDisconnectedPacket)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.ControllerDisconnectedPacket}
   */
  public static final class ControllerDisconnectedPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.ControllerDisconnectedPacket)
      ControllerDisconnectedPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ControllerDisconnectedPacket.newBuilder() to construct.
    private ControllerDisconnectedPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ControllerDisconnectedPacket() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ControllerDisconnectedPacket();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ControllerDisconnectedPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ControllerDisconnectedPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket.class, cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket)) {
        return super.equals(obj);
      }
      cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket other = (cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.ControllerDisconnectedPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.ControllerDisconnectedPacket)
        cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ControllerDisconnectedPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ControllerDisconnectedPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket.class, cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket.Builder.class);
      }

      // Construct using cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ControllerDisconnectedPacket_descriptor;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket getDefaultInstanceForType() {
        return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket.getDefaultInstance();
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket build() {
        cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket buildPartial() {
        cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket result = new cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket) {
          return mergeFrom((cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket other) {
        if (other == cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.ControllerDisconnectedPacket)
    }

    // @@protoc_insertion_point(class_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.ControllerDisconnectedPacket)
    private static final cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket();
    }

    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ControllerDisconnectedPacket>
        PARSER = new com.google.protobuf.AbstractParser<ControllerDisconnectedPacket>() {
      @java.lang.Override
      public ControllerDisconnectedPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ControllerDisconnectedPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ControllerDisconnectedPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.ControllerDisconnectedPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface KeyEventPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.KeyEventPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Common.KeyEventType key_event_type = 1;</code>
     * @return The enum numeric value on the wire for keyEventType.
     */
    int getKeyEventTypeValue();
    /**
     * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Common.KeyEventType key_event_type = 1;</code>
     * @return The keyEventType.
     */
    cn.gdrfgdrf.Protobuf.Common.EnumProto.KeyEventType getKeyEventType();

    /**
     * <code>int32 id = 2;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int64 when = 3;</code>
     * @return The when.
     */
    long getWhen();

    /**
     * <code>int32 modifiers = 4;</code>
     * @return The modifiers.
     */
    int getModifiers();

    /**
     * <code>int32 key_code = 5;</code>
     * @return The keyCode.
     */
    int getKeyCode();

    /**
     * <code>string key_char = 6;</code>
     * @return The keyChar.
     */
    java.lang.String getKeyChar();
    /**
     * <code>string key_char = 6;</code>
     * @return The bytes for keyChar.
     */
    com.google.protobuf.ByteString
        getKeyCharBytes();

    /**
     * <code>int32 key_location = 7;</code>
     * @return The keyLocation.
     */
    int getKeyLocation();
  }
  /**
   * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.KeyEventPacket}
   */
  public static final class KeyEventPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.KeyEventPacket)
      KeyEventPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KeyEventPacket.newBuilder() to construct.
    private KeyEventPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KeyEventPacket() {
      keyEventType_ = 0;
      keyChar_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new KeyEventPacket();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_KeyEventPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_KeyEventPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket.class, cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket.Builder.class);
    }

    public static final int KEY_EVENT_TYPE_FIELD_NUMBER = 1;
    private int keyEventType_ = 0;
    /**
     * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Common.KeyEventType key_event_type = 1;</code>
     * @return The enum numeric value on the wire for keyEventType.
     */
    @java.lang.Override public int getKeyEventTypeValue() {
      return keyEventType_;
    }
    /**
     * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Common.KeyEventType key_event_type = 1;</code>
     * @return The keyEventType.
     */
    @java.lang.Override public cn.gdrfgdrf.Protobuf.Common.EnumProto.KeyEventType getKeyEventType() {
      cn.gdrfgdrf.Protobuf.Common.EnumProto.KeyEventType result = cn.gdrfgdrf.Protobuf.Common.EnumProto.KeyEventType.forNumber(keyEventType_);
      return result == null ? cn.gdrfgdrf.Protobuf.Common.EnumProto.KeyEventType.UNRECOGNIZED : result;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_ = 0;
    /**
     * <code>int32 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int WHEN_FIELD_NUMBER = 3;
    private long when_ = 0L;
    /**
     * <code>int64 when = 3;</code>
     * @return The when.
     */
    @java.lang.Override
    public long getWhen() {
      return when_;
    }

    public static final int MODIFIERS_FIELD_NUMBER = 4;
    private int modifiers_ = 0;
    /**
     * <code>int32 modifiers = 4;</code>
     * @return The modifiers.
     */
    @java.lang.Override
    public int getModifiers() {
      return modifiers_;
    }

    public static final int KEY_CODE_FIELD_NUMBER = 5;
    private int keyCode_ = 0;
    /**
     * <code>int32 key_code = 5;</code>
     * @return The keyCode.
     */
    @java.lang.Override
    public int getKeyCode() {
      return keyCode_;
    }

    public static final int KEY_CHAR_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object keyChar_ = "";
    /**
     * <code>string key_char = 6;</code>
     * @return The keyChar.
     */
    @java.lang.Override
    public java.lang.String getKeyChar() {
      java.lang.Object ref = keyChar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyChar_ = s;
        return s;
      }
    }
    /**
     * <code>string key_char = 6;</code>
     * @return The bytes for keyChar.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyCharBytes() {
      java.lang.Object ref = keyChar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyChar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_LOCATION_FIELD_NUMBER = 7;
    private int keyLocation_ = 0;
    /**
     * <code>int32 key_location = 7;</code>
     * @return The keyLocation.
     */
    @java.lang.Override
    public int getKeyLocation() {
      return keyLocation_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (keyEventType_ != cn.gdrfgdrf.Protobuf.Common.EnumProto.KeyEventType.PRESSED.getNumber()) {
        output.writeEnum(1, keyEventType_);
      }
      if (id_ != 0) {
        output.writeInt32(2, id_);
      }
      if (when_ != 0L) {
        output.writeInt64(3, when_);
      }
      if (modifiers_ != 0) {
        output.writeInt32(4, modifiers_);
      }
      if (keyCode_ != 0) {
        output.writeInt32(5, keyCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(keyChar_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, keyChar_);
      }
      if (keyLocation_ != 0) {
        output.writeInt32(7, keyLocation_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (keyEventType_ != cn.gdrfgdrf.Protobuf.Common.EnumProto.KeyEventType.PRESSED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, keyEventType_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (when_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, when_);
      }
      if (modifiers_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, modifiers_);
      }
      if (keyCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, keyCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(keyChar_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, keyChar_);
      }
      if (keyLocation_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, keyLocation_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket)) {
        return super.equals(obj);
      }
      cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket other = (cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket) obj;

      if (keyEventType_ != other.keyEventType_) return false;
      if (getId()
          != other.getId()) return false;
      if (getWhen()
          != other.getWhen()) return false;
      if (getModifiers()
          != other.getModifiers()) return false;
      if (getKeyCode()
          != other.getKeyCode()) return false;
      if (!getKeyChar()
          .equals(other.getKeyChar())) return false;
      if (getKeyLocation()
          != other.getKeyLocation()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_EVENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + keyEventType_;
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + WHEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getWhen());
      hash = (37 * hash) + MODIFIERS_FIELD_NUMBER;
      hash = (53 * hash) + getModifiers();
      hash = (37 * hash) + KEY_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getKeyCode();
      hash = (37 * hash) + KEY_CHAR_FIELD_NUMBER;
      hash = (53 * hash) + getKeyChar().hashCode();
      hash = (37 * hash) + KEY_LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getKeyLocation();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.KeyEventPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.KeyEventPacket)
        cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_KeyEventPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_KeyEventPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket.class, cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket.Builder.class);
      }

      // Construct using cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        keyEventType_ = 0;
        id_ = 0;
        when_ = 0L;
        modifiers_ = 0;
        keyCode_ = 0;
        keyChar_ = "";
        keyLocation_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_KeyEventPacket_descriptor;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket getDefaultInstanceForType() {
        return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket.getDefaultInstance();
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket build() {
        cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket buildPartial() {
        cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket result = new cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.keyEventType_ = keyEventType_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.when_ = when_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.modifiers_ = modifiers_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.keyCode_ = keyCode_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.keyChar_ = keyChar_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.keyLocation_ = keyLocation_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket) {
          return mergeFrom((cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket other) {
        if (other == cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket.getDefaultInstance()) return this;
        if (other.keyEventType_ != 0) {
          setKeyEventTypeValue(other.getKeyEventTypeValue());
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getWhen() != 0L) {
          setWhen(other.getWhen());
        }
        if (other.getModifiers() != 0) {
          setModifiers(other.getModifiers());
        }
        if (other.getKeyCode() != 0) {
          setKeyCode(other.getKeyCode());
        }
        if (!other.getKeyChar().isEmpty()) {
          keyChar_ = other.keyChar_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.getKeyLocation() != 0) {
          setKeyLocation(other.getKeyLocation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                keyEventType_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                when_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                modifiers_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                keyCode_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                keyChar_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 56: {
                keyLocation_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int keyEventType_ = 0;
      /**
       * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Common.KeyEventType key_event_type = 1;</code>
       * @return The enum numeric value on the wire for keyEventType.
       */
      @java.lang.Override public int getKeyEventTypeValue() {
        return keyEventType_;
      }
      /**
       * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Common.KeyEventType key_event_type = 1;</code>
       * @param value The enum numeric value on the wire for keyEventType to set.
       * @return This builder for chaining.
       */
      public Builder setKeyEventTypeValue(int value) {
        keyEventType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Common.KeyEventType key_event_type = 1;</code>
       * @return The keyEventType.
       */
      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Common.EnumProto.KeyEventType getKeyEventType() {
        cn.gdrfgdrf.Protobuf.Common.EnumProto.KeyEventType result = cn.gdrfgdrf.Protobuf.Common.EnumProto.KeyEventType.forNumber(keyEventType_);
        return result == null ? cn.gdrfgdrf.Protobuf.Common.EnumProto.KeyEventType.UNRECOGNIZED : result;
      }
      /**
       * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Common.KeyEventType key_event_type = 1;</code>
       * @param value The keyEventType to set.
       * @return This builder for chaining.
       */
      public Builder setKeyEventType(cn.gdrfgdrf.Protobuf.Common.EnumProto.KeyEventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        keyEventType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.cn.gdrfgdrf.connectComputer.Protobuf.Common.KeyEventType key_event_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyEventType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        keyEventType_ = 0;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 2;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private long when_ ;
      /**
       * <code>int64 when = 3;</code>
       * @return The when.
       */
      @java.lang.Override
      public long getWhen() {
        return when_;
      }
      /**
       * <code>int64 when = 3;</code>
       * @param value The when to set.
       * @return This builder for chaining.
       */
      public Builder setWhen(long value) {

        when_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 when = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWhen() {
        bitField0_ = (bitField0_ & ~0x00000004);
        when_ = 0L;
        onChanged();
        return this;
      }

      private int modifiers_ ;
      /**
       * <code>int32 modifiers = 4;</code>
       * @return The modifiers.
       */
      @java.lang.Override
      public int getModifiers() {
        return modifiers_;
      }
      /**
       * <code>int32 modifiers = 4;</code>
       * @param value The modifiers to set.
       * @return This builder for chaining.
       */
      public Builder setModifiers(int value) {

        modifiers_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 modifiers = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearModifiers() {
        bitField0_ = (bitField0_ & ~0x00000008);
        modifiers_ = 0;
        onChanged();
        return this;
      }

      private int keyCode_ ;
      /**
       * <code>int32 key_code = 5;</code>
       * @return The keyCode.
       */
      @java.lang.Override
      public int getKeyCode() {
        return keyCode_;
      }
      /**
       * <code>int32 key_code = 5;</code>
       * @param value The keyCode to set.
       * @return This builder for chaining.
       */
      public Builder setKeyCode(int value) {

        keyCode_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 key_code = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyCode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        keyCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object keyChar_ = "";
      /**
       * <code>string key_char = 6;</code>
       * @return The keyChar.
       */
      public java.lang.String getKeyChar() {
        java.lang.Object ref = keyChar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          keyChar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key_char = 6;</code>
       * @return The bytes for keyChar.
       */
      public com.google.protobuf.ByteString
          getKeyCharBytes() {
        java.lang.Object ref = keyChar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          keyChar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key_char = 6;</code>
       * @param value The keyChar to set.
       * @return This builder for chaining.
       */
      public Builder setKeyChar(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        keyChar_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string key_char = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyChar() {
        keyChar_ = getDefaultInstance().getKeyChar();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string key_char = 6;</code>
       * @param value The bytes for keyChar to set.
       * @return This builder for chaining.
       */
      public Builder setKeyCharBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        keyChar_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private int keyLocation_ ;
      /**
       * <code>int32 key_location = 7;</code>
       * @return The keyLocation.
       */
      @java.lang.Override
      public int getKeyLocation() {
        return keyLocation_;
      }
      /**
       * <code>int32 key_location = 7;</code>
       * @param value The keyLocation to set.
       * @return This builder for chaining.
       */
      public Builder setKeyLocation(int value) {

        keyLocation_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>int32 key_location = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyLocation() {
        bitField0_ = (bitField0_ & ~0x00000040);
        keyLocation_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.KeyEventPacket)
    }

    // @@protoc_insertion_point(class_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.KeyEventPacket)
    private static final cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket();
    }

    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KeyEventPacket>
        PARSER = new com.google.protobuf.AbstractParser<KeyEventPacket>() {
      @java.lang.Override
      public KeyEventPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<KeyEventPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KeyEventPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.KeyEventPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TerminalClosedPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.TerminalClosedPacket)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.TerminalClosedPacket}
   */
  public static final class TerminalClosedPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.TerminalClosedPacket)
      TerminalClosedPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TerminalClosedPacket.newBuilder() to construct.
    private TerminalClosedPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TerminalClosedPacket() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TerminalClosedPacket();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_TerminalClosedPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_TerminalClosedPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket.class, cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket)) {
        return super.equals(obj);
      }
      cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket other = (cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.TerminalClosedPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.TerminalClosedPacket)
        cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_TerminalClosedPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_TerminalClosedPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket.class, cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket.Builder.class);
      }

      // Construct using cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_TerminalClosedPacket_descriptor;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket getDefaultInstanceForType() {
        return cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket.getDefaultInstance();
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket build() {
        cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket buildPartial() {
        cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket result = new cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket) {
          return mergeFrom((cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket other) {
        if (other == cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.TerminalClosedPacket)
    }

    // @@protoc_insertion_point(class_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Controller.TerminalClosedPacket)
    private static final cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket();
    }

    public static cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TerminalClosedPacket>
        PARSER = new com.google.protobuf.AbstractParser<TerminalClosedPacket>() {
      @java.lang.Override
      public TerminalClosedPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TerminalClosedPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TerminalClosedPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.gdrfgdrf.Protobuf.Action.Controller.ControllerProto.TerminalClosedPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ConnectComputerPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ConnectComputerPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ControllerDisconnectedPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ControllerDisconnectedPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_KeyEventPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_KeyEventPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_TerminalClosedPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_TerminalClosedPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"Action/Controller/controller.proto\0226cn" +
      ".gdrfgdrf.connectComputer.Protobuf.Actio" +
      "n.Controller\032\021Common/enum.proto\"#\n\025Conne" +
      "ctComputerPacket\022\n\n\002id\030\001 \001(\005\"\036\n\034Controll" +
      "erDisconnectedPacket\"\312\001\n\016KeyEventPacket\022" +
      "Q\n\016key_event_type\030\001 \001(\01629.cn.gdrfgdrf.co" +
      "nnectComputer.Protobuf.Common.KeyEventTy" +
      "pe\022\n\n\002id\030\002 \001(\005\022\014\n\004when\030\003 \001(\003\022\021\n\tmodifier" +
      "s\030\004 \001(\005\022\020\n\010key_code\030\005 \001(\005\022\020\n\010key_char\030\006 " +
      "\001(\t\022\024\n\014key_location\030\007 \001(\005\"\026\n\024TerminalClo" +
      "sedPacketB9\n&cn.gdrfgdrf.Protobuf.Action" +
      ".ControllerB\017ControllerProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.gdrfgdrf.Protobuf.Common.EnumProto.getDescriptor(),
        });
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ConnectComputerPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ConnectComputerPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ConnectComputerPacket_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ControllerDisconnectedPacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ControllerDisconnectedPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_ControllerDisconnectedPacket_descriptor,
        new java.lang.String[] { });
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_KeyEventPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_KeyEventPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_KeyEventPacket_descriptor,
        new java.lang.String[] { "KeyEventType", "Id", "When", "Modifiers", "KeyCode", "KeyChar", "KeyLocation", });
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_TerminalClosedPacket_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_TerminalClosedPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Controller_TerminalClosedPacket_descriptor,
        new java.lang.String[] { });
    cn.gdrfgdrf.Protobuf.Common.EnumProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
