// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Action/Account/error.proto

package cn.gdrfgdrf.Protobuf.Action.Account;

public final class AccountErrorProto {
  private AccountErrorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginFailedPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.LoginFailedPacket)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.LoginFailedPacket}
   */
  public static final class LoginFailedPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.LoginFailedPacket)
      LoginFailedPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginFailedPacket.newBuilder() to construct.
    private LoginFailedPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginFailedPacket() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginFailedPacket();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_LoginFailedPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_LoginFailedPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket.class, cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket)) {
        return super.equals(obj);
      }
      cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket other = (cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.LoginFailedPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.LoginFailedPacket)
        cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_LoginFailedPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_LoginFailedPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket.class, cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket.Builder.class);
      }

      // Construct using cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_LoginFailedPacket_descriptor;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket getDefaultInstanceForType() {
        return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket.getDefaultInstance();
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket build() {
        cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket buildPartial() {
        cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket result = new cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket) {
          return mergeFrom((cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket other) {
        if (other == cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.LoginFailedPacket)
    }

    // @@protoc_insertion_point(class_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.LoginFailedPacket)
    private static final cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket();
    }

    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginFailedPacket>
        PARSER = new com.google.protobuf.AbstractParser<LoginFailedPacket>() {
      @java.lang.Override
      public LoginFailedPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LoginFailedPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginFailedPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.LoginFailedPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TokenInvalidPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.TokenInvalidPacket)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.TokenInvalidPacket}
   */
  public static final class TokenInvalidPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.TokenInvalidPacket)
      TokenInvalidPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TokenInvalidPacket.newBuilder() to construct.
    private TokenInvalidPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TokenInvalidPacket() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TokenInvalidPacket();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenInvalidPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenInvalidPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket.class, cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket)) {
        return super.equals(obj);
      }
      cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket other = (cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.TokenInvalidPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.TokenInvalidPacket)
        cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenInvalidPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenInvalidPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket.class, cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket.Builder.class);
      }

      // Construct using cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenInvalidPacket_descriptor;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket getDefaultInstanceForType() {
        return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket.getDefaultInstance();
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket build() {
        cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket buildPartial() {
        cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket result = new cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket) {
          return mergeFrom((cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket other) {
        if (other == cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.TokenInvalidPacket)
    }

    // @@protoc_insertion_point(class_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.TokenInvalidPacket)
    private static final cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket();
    }

    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TokenInvalidPacket>
        PARSER = new com.google.protobuf.AbstractParser<TokenInvalidPacket>() {
      @java.lang.Override
      public TokenInvalidPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TokenInvalidPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TokenInvalidPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenInvalidPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TokenExpiredPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.TokenExpiredPacket)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.TokenExpiredPacket}
   */
  public static final class TokenExpiredPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.TokenExpiredPacket)
      TokenExpiredPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TokenExpiredPacket.newBuilder() to construct.
    private TokenExpiredPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TokenExpiredPacket() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TokenExpiredPacket();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenExpiredPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenExpiredPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket.class, cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket)) {
        return super.equals(obj);
      }
      cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket other = (cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.TokenExpiredPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.TokenExpiredPacket)
        cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenExpiredPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenExpiredPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket.class, cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket.Builder.class);
      }

      // Construct using cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenExpiredPacket_descriptor;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket getDefaultInstanceForType() {
        return cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket.getDefaultInstance();
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket build() {
        cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket buildPartial() {
        cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket result = new cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket) {
          return mergeFrom((cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket other) {
        if (other == cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.TokenExpiredPacket)
    }

    // @@protoc_insertion_point(class_scope:cn.gdrfgdrf.connectComputer.Protobuf.Action.Account.Error.TokenExpiredPacket)
    private static final cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket();
    }

    public static cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TokenExpiredPacket>
        PARSER = new com.google.protobuf.AbstractParser<TokenExpiredPacket>() {
      @java.lang.Override
      public TokenExpiredPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TokenExpiredPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TokenExpiredPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.gdrfgdrf.Protobuf.Action.Account.AccountErrorProto.TokenExpiredPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_LoginFailedPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_LoginFailedPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenInvalidPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenInvalidPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenExpiredPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenExpiredPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032Action/Account/error.proto\0229cn.gdrfgdr" +
      "f.connectComputer.Protobuf.Action.Accoun" +
      "t.Error\"\023\n\021LoginFailedPacket\"\024\n\022TokenInv" +
      "alidPacket\"\024\n\022TokenExpiredPacketB8\n#cn.g" +
      "drfgdrf.Protobuf.Action.AccountB\021Account" +
      "ErrorProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_LoginFailedPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_LoginFailedPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_LoginFailedPacket_descriptor,
        new java.lang.String[] { });
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenInvalidPacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenInvalidPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenInvalidPacket_descriptor,
        new java.lang.String[] { });
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenExpiredPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenExpiredPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_gdrfgdrf_connectComputer_Protobuf_Action_Account_Error_TokenExpiredPacket_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
